server:
  port: 9006
spring:
  application:
    name: tessquare-spit #服务名
  data:
    mongodb:
      host: 192.168.184.134
      database: spitdb
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true